### ISSUE TITLE
SwalComponent not working as intended

### ISSUE THREAD

**Issue by WaseemRkab** [sweetalert2/ngx-sweetalert2#152]
when i declare SwalComponent in declerations in app module got this error immediately on the console on web.
im using Angular 9.

core.js:610 Uncaught Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
    at getCompilerFacade (core.js:610)
    at Function.get (core.js:38849)
    at getNgModuleDef (core.js:2195)
    at assertNgModuleType (core.js:2933)
    at compileNgModuleFactory__POST_R3__ (core.js:41864)
    at PlatformRef.bootstrapModule (core.js:42231)
    at Module../src/main.ts (main.ts:11)
    at __webpack_require__ (bootstrap:84)
    at Object.0 (main.ts:12)
    at __webpack_require__ (bootstrap:84)

this is my app.module.ts

import {BrowserModule} from '@angular/platform-browser';
import {NgModule} from '@angular/core';

import {AppComponent} from './app.component';
import {FormsModule, ReactiveFormsModule} from '@angular/forms';
import {AlertComponent} from './alert/alert.component';
import {SwalComponent, SweetAlert2Module} from '@sweetalert2/ngx-sweetalert2';

@NgModule({
  declarations: [
    AppComponent,
    AlertComponent,
    SwalComponent
  ],
  imports: [
    BrowserModule,
    ReactiveFormsModule,
    FormsModule,
    SweetAlert2Module.forRoot(),
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
}

package.json
{
  "name": "array-project",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.0.2",
    "@angular/common": "~9.0.2",
    "@angular/compiler": "~9.0.2",
    "@angular/core": "~9.0.2",
    "@angular/forms": "~9.0.2",
    "@angular/platform-browser": "~9.0.2",
    "@angular/platform-browser-dynamic": "~9.0.2",
    "@angular/router": "~9.0.2",
    "@sweetalert2/ngx-sweetalert2": "^8.0.0",
    "bootstrap": "^4.4.1",
    "cors": "^2.8.5",
    "fs": "0.0.1-security",
    "rxjs": "~6.5.4",
    "sweetalert2": "^9.8.2",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.3",
    "@angular/cli": "~9.0.3",
    "@angular/compiler-cli": "~9.0.2",
    "@angular/language-service": "~9.0.2",
    "@types/fs-extra": "^8.1.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^13.7.7",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~5.18.0",
    "typescript": "~3.7.5"
  }
}
tsconfig
{
  "compileOnSave": true,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "es2015",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2020",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2020",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}

**Comment by toverux** [comment]
Hello,

You do not need to add SwalComponent to your declaration, as importing the module already does that. Modules are just a way to declare a bunch of things for you implicitly.
Could you remove it and tell me if there's another problem?

**Comment by WaseemRkab** [comment]
> Hello,
> 
> You do not need to/must not add SwalComponent to your declarations array, as importing the module already does that. Modules are just a way to declare a bunch of things for you implicitly.
> Could you remove it and tell me if there's another problem?

after i removed SwalComponent from deceleration i have this error which printed twice now in console
NullInjectorError: R3InjectorError(AppModule)[SweetAlert2LoaderService -> SweetAlert2LoaderService -> SweetAlert2LoaderService]: 
  NullInjectorError: No provider for SweetAlert2LoaderService!
    at NullInjector.get (http://localhost:4200/vendor.js:8183:27)
    at R3Injector.get (http://localhost:4200/vendor.js:21906:33)
    at R3Injector.get (http://localhost:4200/vendor.js:21906:33)
    at R3Injector.get (http://localhost:4200/vendor.js:21906:33)
    at NgModuleRef$1.get (http://localhost:4200/vendor.js:39241:33)
    at Object.get (http://localhost:4200/vendor.js:37088:35)
    at getOrCreateInjectable (http://localhost:4200/vendor.js:11712:39)
    at Module.ɵɵdirectiveInject (http://localhost:4200/vendor.js:25814:12)
    at NodeInjectorFactory.SwalComponent_Factory [as factory] (http://localhost:4200/vendor.js:61856:153)
    at getNodeInjectable (http://localhost:4200/vendor.js:11857:44)

**Comment by WaseemRkab** [comment]
when i provide the SweetAlert2LoaderService in providers array on module.ts
i have this error in console too.
R3InjectorError(AppModule)[SweetAlert2LoaderService -> InjectionToken @sweetalert2/ngx-sweetalert2#swalProvider -> InjectionToken @sweetalert2/ngx-sweetalert2#swalProvider -> InjectionToken @sweetalert2/ngx-sweetalert2#swalProvider]: 
  NullInjectorError: No provider for InjectionToken @sweetalert2/ngx-sweetalert2#swalProvider!
    at NullInjector.get (http://localhost:4200/vendor.js:8183:27)
    at R3Injector.get (http://localhost:4200/vendor.js:21906:33)
    at R3Injector.get (http://localhost:4200/vendor.js:21906:33)
    at R3Injector.get (http://localhost:4200/vendor.js:21906:33)
    at injectInjectorOnly (http://localhost:4200/vendor.js:8038:33)
    at Module.ɵɵinject (http://localhost:4200/vendor.js:8048:57)
    at Object.SweetAlert2LoaderService_Factory [as factory] (http://localhost:4200/vendor.js:61587:177)
    at R3Injector.hydrate (http://localhost:4200/vendor.js:22133:63)
    at R3Injector.get (http://localhost:4200/vendor.js:21894:33)
    at NgModuleRef$1.get (http://localhost:4200/vendor.js:39241:33)

**Comment by toverux** [comment]
You still use .forRoot() right?

Eventually, could you send me a project as a .zip that reproduces the problem?

**Comment by WaseemRkab** [comment]
> You still use .forRoot() right?
> 
> Eventually, could you send me a project as a .zip that reproduces the problem?

yes, now everything seems to work after i restarted server
thanks for help.
