### ISSUE TITLE
Angular 17 - Stanalone components

### ISSUE THREAD

**Issue by bdavilainnovating** [sweetalert2/ngx-sweetalert2#256]
I just moved my project to angular 17, in addition to that I made all my components to be standalone, now my component looks like this 

```
imports: [
    SweetAlert2Module,
  ],
providers: [SweetAlert2LoaderService]
```

I am getting this error 
ERROR NullInjectorError: R3InjectorError(Standalone[Component])[InjectionToken @sweetalert2/ngx-sweetalert2#swalProvider -> InjectionToken @sweetalert2/ngx-sweetalert2#swalProvider -> InjectionToken @sweetalert2/ngx-sweetalert2#swalProvider -> InjectionToken @sweetalert2/ngx-sweetalert2#swalProvider]: 
NullInjectorError: No provider for InjectionToken @sweetalert2/ngx-sweetalert2#swalProvider!

When I remove the provider then I get this error 

error_handler.ts:45 ERROR NullInjectorError: R3InjectorError(Standalone[Component])[_SweetAlert2LoaderService -> _SweetAlert2LoaderService -> _SweetAlert2LoaderService -> _SweetAlert2LoaderService]: 
  NullInjectorError: No provider for _SweetAlert2LoaderService!
    at NullInjector.get (null_injector.ts:16:21)
    at R3Injector.get (r3_injector.ts:300:27)
    at R3Injector.get (r3_injector.ts:300:27)
    at R3Injector.get (r3_injector.ts:300:27)
    at R3Injector.get (r3_injector.ts:300:27)
    at injector_injector.get (component_ref.ts:109:32)
    at lookupTokenUsingModuleInjector (di.ts:371:31)
    in getOrCreateInjectable (di.ts:423:10)
    at ɵɵdirectiveInject (di.ts:55:7)
    at NodeInjectorFactory.SwalComponent_Factory [as factory] (sweetalert2-loader.service.ts:12:14)

**Comment by shadow1349** [comment]
in you app.config.ts if you add `SweetAlert2Module.forRoot()` in `importProvidersFrom([])` array it should go away.
