### ISSUE TITLE
Angular 19 support

### ISSUE THREAD

**Issue by rdamazio** [sweetalert2/ngx-sweetalert2#268]
Angular 19 is out! :) But it seems that this package is currently restricted to 18 :(
Can we get an update to the latest version?

I'm happy to send a PR if you'd like, but it seems there aren't a lot of tests here, so I'm hesitant that I'll be able to test properly that nothing breaks.

Thanks in advance

**Comment by limonte** [comment]
PRs are welcome 🤗 thank you!

**Comment by rdamazio** [comment]
I tried to just add the new version to projects/ngx-sweetalert2/package.json, but it crashes at startup with my app, even though the tests on this repo pass :(

```
NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
    at injectInjectorOnly (/Users/rdamazio/Development/efis-editor/.angular/cache/19.0.0/efis-editor/vite/deps_ssr/@sweetalert2_ngx-sweetalert2.js:11728:11)
    at ɵɵinject (/Users/rdamazio/Development/efis-editor/.angular/cache/19.0.0/efis-editor/vite/deps_ssr/@sweetalert2_ngx-sweetalert2.js:11736:59)
    at ɵɵdirectiveInject (/Users/rdamazio/Development/efis-editor/.angular/cache/19.0.0/efis-editor/vite/deps_ssr/@sweetalert2_ngx-sweetalert2.js:16935:12)
    at NodeInjectorFactory.SwalDirective_Factory (/Users/rdamazio/Development/efis-editor/.angular/cache/19.0.0/efis-editor/vite/deps_ssr/@sweetalert2_ngx-sweetalert2.js:32182:54)
```

It could be something on my side, but unfortunately I won't be able to debug this any time soon :/ so I'll let you perform the upgrade.

**Comment by rdamazio** [comment]
Made a few more attempts, but I don't understand what it wants here - it seems to be related to the move to standalone components, and its inability to inject the loader service at construction time? My app and its tests do import the module though, and I did try changing everything to standalone: false on ngx-sweetalert2.

```
Chrome Headless 131.0.0.0 (Mac OS 10.15.7) NodeComponent should create FAILED
	Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.dev/errors/NG0203
	error properties: Object({ code: -203 })
	    at injectInjectorOnly (node_modules/@angular/core/fesm2022/core.mjs:1104:15)
	    at ɵɵinject (node_modules/@angular/core/fesm2022/core.mjs:1117:60)
	    at Module.ɵɵdirectiveInject (node_modules/@angular/core/fesm2022/core.mjs:12953:16)
	    at NodeInjectorFactory.factory (ngx-sweetalert2/projects/ngx-sweetalert2/src/lib/sweetalert2-loader.service.ts:14:14)
	    at getNodeInjectable (node_modules/@angular/core/fesm2022/core.mjs:5433:44)
	    at instantiateAllDirectives (node_modules/@angular/core/fesm2022/core.mjs:13827:27)
	    at createDirectivesInstances (node_modules/@angular/core/fesm2022/core.mjs:13223:5)
	    at ɵɵelementStart (node_modules/@angular/core/fesm2022/core.mjs:27718:9)
	    at templateFn (ng:///ChecklistTreeNodeComponent.js:84:5)
	    at executeTemplate (node_modules/@angular/core/fesm2022/core.mjs:13183:9)
```

**Comment by limonte** [comment]
Thank you so much for putting your time into investigating this @rdamazio 

What you described in your report indicates that a new major release of this library would be needed to Angular 19.

There's no chance I can find the required for this task time and energy 😢 

---

### This project is now looking for a maintainer(s): https://github.com/sweetalert2/ngx-sweetalert2/issues/269

Anyone who's willing to give this repo a new life is very welcome 🙌

**Comment by FACode** [comment]
Hey everyone, 
I'm not sure who is taking care of this repo (I saw issue #269) but I created a PR with
the update for this awesome package to Angular 19. 

Check this PR -> #271 

@rdamazio maybe this will help you ;) 
@limonte Please have a look over my pull request, it will be great to wrap it up and release it

Cheers!

**Comment by rdamazio** [comment]
> @rdamazio maybe this will help you ;)

Thanks! At this point I've migrated off of this package, but I'll watch it and maybe adopt it again :)

**Comment by limonte** [comment]
@FACode's contribution seems to work well, so there's Angular 19 support now in the latest major release 🎉
