### ISSUE TITLE
Module build failed: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by grubitania** [sweetalert2/ngx-sweetalert2#64]
When trying to build app, this happens

**ng build --prod**

ERROR in ./node_modules/sweetalert2/dist/sweetalert2.all.js
Module build failed: RangeError: Maximum call stack size exceeded
    at Object.visitEachChild (C:\Users\User\Desktop\projekti\danas-radim-test\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:51169:28)
    at visitor (C:\Users\User\Desktop\projekti\danas-radim-test\node_modules\@angular-devkit\build-optimizer\src\transforms\import-tslib.js:33:27)
    at visitNode (C:\Users\User\Desktop\projekti\danas-radim-test\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:51053:23)
    at Object.visitEachChild (C:\Users\User\Desktop\projekti\danas-radim-test\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:51289:46)
    at visitor (C:\Users\User\Desktop\projekti\danas-radim-test\node_modules\@angular-devkit\build-optimizer\src\transforms\import-tslib.js:33:27)
    at visitNode (C:\Users\User\Desktop\projekti\danas-radim-test\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:51053:23)
    at Object.visitEachChild (C:\Users\User\Desktop\projekti\danas-radim-test\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:51289:46)
    at visitor (C:\Users\User\Desktop\projekti\danas-radim-test\node_modules\@angular-devkit\build-optimizer\src\transforms\import-tslib.js:33:27)
    at visitNode (C:\Users\User\Desktop\projekti\danas-radim-test\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:51053:23)
    at Object.visitEachChild (C:\Users\User\Desktop\projekti\danas-radim-test\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:51289:46)
    at visitor (C:\Users\User\Desktop\projekti\danas-radim-test\node_modules\@angular-devkit\build-optimizer\src\transforms\import-tslib.js:33:27)
    at visitNode (C:\Users\User\Desktop\projekti\danas-radim-test\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:51053:23)
    at Object.visitEachChild (C:\Users\User\Desktop\projekti\danas-radim-test\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:51289:46)
    at visitor (C:\Users\User\Desktop\projekti\danas-radim-test\node_modules\@angular-devkit\build-optimizer\src\transforms\import-tslib.js:33:27)
    at visitNode (C:\Users\User\Desktop\projekti\danas-radim-test\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:51053:23)
    at Object.visitEachChild (C:\Users\User\Desktop\projekti\danas-radim-test\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:51289:46)
 @ ./node_modules/@toverux/ngx-sweetalert2/esm5/toverux-ngx-sweetalert2.js 1:0-31
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts

**Comment by asfo** [comment]
I'm having the same issue...

But when I just recompile it works correctly, I don't know why

**Comment by toverux** [comment]
This is a SweetAlert2 issue, but probably a bug of TypeScript. If that's still an issue, please open a new one in Swal2's repository.

**Comment by stephanecot** [comment]
I don't know if disabling build-optimizer is a good solution, maybe a temp solution...
There is a problem somewhere....
