### ISSUE TITLE
Module build failed: RangeError: Maximum call stack size exceeded at angular 6 with AoT build

### ISSUE THREAD

**Issue by vincent-cm** [sweetalert2/ngx-sweetalert2#72]
sweetalert2.all.js
Module build failed: RangeError: Maximum call stack size exceeded

```
ERROR in ./node_modules/sweetalert2/dist/sweetalert2.all.js
Module build failed: RangeError: Maximum call stack size exceeded
    at emitNodeWithSourceMap (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:68251:39)
    at pipelineEmitWithSourceMap (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:70981:17)
    at emitNodeWithNestedComments (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:68568:17)
    at emitNodeWithSynthesizedComments (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:68518:13)
    at emitNodeWithComments (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:68488:21)
    at pipelineEmitWithComments (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:70973:17)
    at emitNodeWithNotification (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:67902:21)
    at pipelineEmitWithNotification (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:70964:17)
    at emitExpression (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:70960:13)
    at emitBinaryExpression (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:71846:13)
    at pipelineEmitExpression (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:71317:28)
    at pipelineEmitWithHint (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:70991:49)
    at emitNodeWithSourceMap (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:68279:21)
    at pipelineEmitWithSourceMap (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:70981:17)
    at emitNodeWithNestedComments (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:68568:17)
    at emitNodeWithSynthesizedComments (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:68518:13)
    at emitNodeWithComments (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:68488:21)
    at pipelineEmitWithComments (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:70973:17)
    at emitNodeWithNotification (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:67902:21)
    at pipelineEmitWithNotification (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:70964:17)
    at emitExpression (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:70960:13)
    at emitBinaryExpression (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:71846:13)
    at pipelineEmitExpression (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:71317:28)
    at pipelineEmitWithHint (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:70991:49)
    at emitNodeWithSourceMap (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:68279:21)
    at pipelineEmitWithSourceMap (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:70981:17)
    at emitNodeWithNestedComments (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:68568:17)
    at emitNodeWithSynthesizedComments (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:68518:13)
    at emitNodeWithComments (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:68488:21)
    at pipelineEmitWithComments (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:70973:17)
    at emitNodeWithNotification (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:67902:21)
    at pipelineEmitWithNotification (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:70964:17)
    at emitExpression (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:70960:13)
    at emitBinaryExpression (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:71846:13)
    at pipelineEmitExpression (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:71317:28)
    at pipelineEmitWithHint (/project/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:70991:49)
 @ ./node_modules/@toverux/ngx-sweetalert2/esm5/toverux-ngx-sweetalert2.js 1:0-31 6:42-46 7:44-48 8:51-55 9:44-48 10:50-54 11:49-53 12:43-47 34:26-30 63:12-16 77:22-26 111:35-39
 @ ./node_modules/@toverux/ngx-sweetalert2/toverux-ngx-sweetalert2.ngfactory.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.browser.ts
```

**Comment by vincent-cm** [comment]
@mbit0815 downgrade version of sweetalert2

**Comment by limonte** [comment]
There are more details in #64

**Comment by mbit0815** [comment]
@vincent-cm which version did work for you?

**Comment by JWess** [comment]
@vincent-cm How far did you have to downgrade?

**Comment by madibi** [comment]
yesterday i had problem with sweetalert2 , i believe during optimization,  paramName ommited, so i set   <script>
  paramName = [];
  </script>
on top of page and error solved, but today i upgrade sweetalert, and get:
 Maximum call stack size exceeded
