### ISSUE TITLE
AoT build failed on production mode with new versions

### ISSUE THREAD

**Issue by vincent-cm** [sweetalert2/ngx-sweetalert2#74]
"@toverux/ngx-sweetalert2": "^3.4.0",
    "sweetalert2": "^7.20.6",

with angular:

    "@angular/animations": "^6.0.2",
    "@angular/cdk": "^6.0.2",
    "@angular/common": "^6.0.2",
    "@angular/compiler": "^6.0.2",
    "@angular/core": "^6.0.2",
    "@angular/forms": "^6.0.2",
    "@angular/http": "^6.0.2",
    "@angular/material": "^6.0.2",
    "@angular/platform-browser": "^6.0.2",
    "@angular/platform-browser-dynamic": "^6.0.2",
    "@angular/platform-server": "^6.0.2",
    "@angular/router": "^6.0.2",

    "@angular-devkit/build-optimizer": "^0.6.3",
    "@angular/cli": "^6.0.3",
    "@angular/compiler-cli": "^6.0.2",
    "@angular/language-service": "^6.0.2", 

Error message:

```
ERROR in ./node_modules/sweetalert2/dist/sweetalert2.all.js
Module build failed: RangeError: Maximum call stack size exceeded
    at computeLineAndCharacterOfPosition (/Project/node_modules/typescript/lib/typescript.js:6093:47)
    at Object.getLineAndCharacterOfPosition (/Project/node_modules/typescript/lib/typescript.js:6113:16)
    at getLineOfLocalPosition (/Project/node_modules/typescript/lib/typescript.js:10262:19)
    at positionsAreOnSameLine (/Project/node_modules/typescript/lib/typescript.js:10978:13)
    at Object.rangeEndIsOnSameLineAsRangeStart (/Project/node_modules/typescript/lib/typescript.js:10973:16)
    at needsIndentation (/Project/node_modules/typescript/lib/typescript.js:73203:24)
    at emitBinaryExpression (/Project/node_modules/typescript/lib/typescript.js:71844:40)
    at pipelineEmitExpression (/Project/node_modules/typescript/lib/typescript.js:71317:28)
    at pipelineEmitWithHint (/Project/node_modules/typescript/lib/typescript.js:70991:49)
    at emitNodeWithSourceMap (/Project/node_modules/typescript/lib/typescript.js:68279:21)
    at pipelineEmitWithSourceMap (/Project/node_modules/typescript/lib/typescript.js:70981:17)
    at emitNodeWithNestedComments (/Project/node_modules/typescript/lib/typescript.js:68568:17)
    at emitNodeWithSynthesizedComments (/Project/node_modules/typescript/lib/typescript.js:68518:13)
    at emitNodeWithComments (/Project/node_modules/typescript/lib/typescript.js:68488:21)
    at pipelineEmitWithComments (/Project/node_modules/typescript/lib/typescript.js:70973:17)
    at emitNodeWithNotification (/Project/node_modules/typescript/lib/typescript.js:67902:21)
    at pipelineEmitWithNotification (/Project/node_modules/typescript/lib/typescript.js:70964:17)
    at emitExpression (/Project/node_modules/typescript/lib/typescript.js:70960:13)
    at emitBinaryExpression (/Project/node_modules/typescript/lib/typescript.js:71846:13)
    at pipelineEmitExpression (/Project/node_modules/typescript/lib/typescript.js:71317:28)
    at pipelineEmitWithHint (/Project/node_modules/typescript/lib/typescript.js:70991:49)
    at emitNodeWithSourceMap (/Project/node_modules/typescript/lib/typescript.js:68279:21)
    at pipelineEmitWithSourceMap (/Project/node_modules/typescript/lib/typescript.js:70981:17)
    at emitNodeWithNestedComments (/Project/node_modules/typescript/lib/typescript.js:68568:17)
    at emitNodeWithSynthesizedComments (/Project/node_modules/typescript/lib/typescript.js:68518:13)
    at emitNodeWithComments (/Project/node_modules/typescript/lib/typescript.js:68488:21)
    at pipelineEmitWithComments (/Project/node_modules/typescript/lib/typescript.js:70973:17)
    at emitNodeWithNotification (/Project/node_modules/typescript/lib/typescript.js:67902:21)
    at pipelineEmitWithNotification (/Project/node_modules/typescript/lib/typescript.js:70964:17)
    at emitExpression (/Project/node_modules/typescript/lib/typescript.js:70960:13)
    at emitBinaryExpression (/Project/node_modules/typescript/lib/typescript.js:71846:13)
    at pipelineEmitExpression (/Project/node_modules/typescript/lib/typescript.js:71317:28)
    at pipelineEmitWithHint (/Project/node_modules/typescript/lib/typescript.js:70991:49)
    at emitNodeWithSourceMap (/Project/node_modules/typescript/lib/typescript.js:68279:21)
    at pipelineEmitWithSourceMap (/Project/node_modules/typescript/lib/typescript.js:70981:17)
    at emitNodeWithNestedComments (/Project/node_modules/typescript/lib/typescript.js:68568:17)
 @ ./node_modules/@toverux/ngx-sweetalert2/esm5/toverux-ngx-sweetalert2.js 1:0-31 6:42-46 7:44-48 8:51-55 9:44-48 10:50-54 11:49-53 12:43-47 34:26-30 63:12-16 77:22-26 111:35-39
 @ ./node_modules/@toverux/ngx-sweetalert2/toverux-ngx-sweetalert2.ngfactory.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.browser.ts
```

**Comment by JWess** [comment]
What was the fix for this? I am having this issue when trying to build on Heroku, but it doesn't happen in my local environment.
